############################################ DEFAULT
# ?? ????? ???? ??? ??? ??? ????.
spring:
  profiles:
    active: local # default profile? ????.

---
############################################ LOCAL

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
